### ISSUE TITLE
Document `.update()` function fails on JDK 16

### ISSUE THREAD

**Issue by harisarang** [typesense/typesense-java#11]
Document update uses the HTTP PATCH method.
But Jersey does not support the HTTP PATCH method.
So workaround used for now is,
```java
Client client = ClientBuilder.newClient(clientConfig).property(HttpUrlConnectorProvider.SET_METHOD_WORKAROUND, true);
```
This will not work in JDK 16

**Comment by kishorenc** [comment]
Seems fine after switching to `ApacheConnectorProvider`.
