### ISSUE TITLE
makeRequest should throw TypesenseError and not silently catch it

### ISSUE THREAD

**Issue by superkelvint** [typesense/typesense-java#14]
## Description

ApiCall.makeRequest() should throw TypesenseError instead of silently catching it and printing the stacktrace. At the moment, due to this mechanism, there is no way of distinguishing between a collection which doesn't exist and when a collection exists but the api key is wrong as both return null.

## Metadata

**Typsense Version**: 0.21

**OS**: Ubuntu 20.04

**Comment by harisarang** [comment]
@superkelvint 
Thanks for pointing this out ! Will fix this

**Comment by kishorenc** [comment]
Latest version propagates exceptions meaningfully to the caller.
