### ISSUE TITLE
facet_counts has type List<Integer> but json has different shape

### ISSUE THREAD

**Issue by tropikoder** [typesense/typesense-java#19]
## Description
the java lib thinks it's a list of integers
<img width="821" alt="Screen Shot 2022-04-25 at 10 00 51 AM" src="https://user-images.githubusercontent.com/68028161/165130858-d20a6df7-447a-4ca6-a3dd-fbd15c5e07ac.png">

but the json has this shape:
```json
"results": [
        {
            "facet_counts": [
                {
                    "counts": [
                        {
                            "count": 4,
                            "highlighted": "kate spade new york",
                            "value": "kate spade new york"
                        },
                        {
                            "count": 2,
                            "highlighted": "BLU",
                            "value": "BLU"
                        },
                        {
                            "count": 2,
                            "highlighted": "Seidio",
                            "value": "Seidio"
                        },
```

## Steps to reproduce
perform a search with facets, see json

## Expected Behavior
facet counts in library should be a list of a more complex type, not Integer 

## Metadata

**Typsense Version**:

**OS**:

**Comment by kishorenc** [comment]
@tropikoder 

This is fixed here: https://github.com/typesense/typesense-java/releases/tag/0.0.3-rc1

Please try it out and let me know.

Also, I had to migrate field type enum to string constants as part of these changes. This is because the enum values like `string[]` did not produce readable enum names. See how the constants are used in the updated README here: https://github.com/typesense/typesense-java#create-a-new-collection

**Comment by tropikoder** [comment]
there's another mismatch between documentation and current java lib.

https://typesense.org/docs/0.21.0/api/collection-alias.html#create-or-update-an-alias

docs say that the second argument should be of type CollectionAlias but instead it's CollectionAliasSchema

<img width="658" alt="Screen Shot 2022-04-26 at 9 33 55 PM" src="https://user-images.githubusercontent.com/68028161/165434769-6a5c963b-bef4-48df-b27c-f73ee3d5a3e0.png">

**Comment by kishorenc** [comment]
The Java library underwent some changes as we published those docs, so the docs are out of sync. Sorry for the inconvenience: we will fix it.
