### ISSUE TITLE
Unable to bulk import with OkHttpClient change in version > 0.0.6

### ISSUE THREAD

**Issue by graesj** [typesense/typesense-java#29]
## Description
Following the change to OkHttp client in version > 0.0.6 I am unable to bulk import with this library. 

## Steps to reproduce
Created an example to reproduce here:
https://github.com/graesj/typesense-import-multiple-bug

## Metadata

Typesense Version: 0.24.0 - not so relevant I guess
 ** typesense-java version **: any version > 0.0.6

**Comment by kishorenc** [comment]
Fixed in `0.0.10`.
