### ISSUE TITLE
SearchGroupedHit class wrongly assumes the `groupKey` is always a list of strings

### ISSUE THREAD

**Issue by oluwatimilehin** [typesense/typesense-java#31]
I'm using the client and I see in [SearchGroupedHit.java#L34](https://github.com/typesense/typesense-java/blob/be95dbbda40d67495ba5e4f69a960f6a4f73dc13/src/main/java/org/typesense/model/SearchGroupedHit.java#L34) that it expects the `groupKey` to always be a list of String objects, which isn't always the case.  In my dataset for example, the group key is a list of lists. 

I would create a PR to fix this and make it a list of Objects (which I'm aware isn't a backwards-compatible change), but the contributing guide has the line: `NOTE: The model directory is read-only make sure not to edit it.` and the class is in the model directory.

Any chance you can make this change, please?

**Comment by kishorenc** [comment]
I will make this change this week.

**Comment by oluwatimilehin** [comment]
@kishorenc Thanks for the quick turnaround, Kishore. It works well.
