### ISSUE TITLE
Upload the Maven Central for Release Builds

### ISSUE THREAD

**Issue by electricpug** [typesense/typesense-java#4]
## Description

Once the Git flow process is tidied up, we need to add support in the build process for uploading to Maven Central, to make the client available for other projects in an easier fashion.

## Steps to reproduce

1. The Maven site https://maven.apache.org/repository/guide-central-repository-upload.html has some notes. I haven't looked into it too much just yet.

## Expected Behavior

1. Developers should be able to include the typesense-java client in their Maven/Gradle builds with appropriate version numbers and tags.

## Actual Behavior

1. Not currently supported.

## Metadata

**Typsense Version**:

**OS**:

**Comment by TomBeckett** [comment]
@kishorenc Are there any plans for this?

**Comment by kishorenc** [comment]
This is done!

```
<dependency>
    <groupId>org.typesense</groupId>
    <artifactId>typesense-java</artifactId>
    <version>0.0.3</version>
</dependency>
```

**Comment by amalshiwantha** [comment]
hi @kishorenc any idea about this error?

`Duplicate class com.fasterxml.jackson.core.Base64Variant found in modules jetified-jackson-core-2.9.6 (com.fasterxml.jackson.core:jackson-core:2.9.6) and jetified-typesense-java-0.0.3 (typesense-java-0.0.3.jar)`
