### ISSUE TITLE
Set default sort=true for numeric and boolean types

### ISSUE THREAD

**Issue by imalao** [typesense/typesense-java#40]
## Description

The Typesense docs say sorting is enabled by default on numeric and boolean fields ([link](https://typesense.org/docs/0.23.1/api/search.html#sorting-on-strings)). The java client has sort=false as the default for all fields. 

## Steps to reproduce

See https://github.com/typesense/typesense-java/blob/master/src/main/java/org/typesense/model/Field.java#L37

## Expected Behavior

For numeric and boolean types, sort=true is the default.

## Actual Behavior

sort=false is the default for all field types.

## Metadata

**Typesense Version**: n/a

**OS**: n/a

**Comment by kishorenc** [comment]
Fixed in `v0.3.0`
