### ISSUE TITLE
Preset feature is not available

### ISSUE THREAD

**Issue by nathan-shields** [typesense/typesense-java#41]
## Description

"Presets" are not implemented on the Java SDK. Even if I create a preset, there's no way I can add it to `SearchParameters` https://github.com/typesense/typesense-java/blob/master/src/main/java/org/typesense/model/SearchParameters.java.

## Steps to reproduce

Not Applicable

## Expected Behavior

I expect to be able to utilize the Presets feature from the Java SDK

## Actual Behavior

Not Applicable

## Metadata

**Typesense Version**:  `0.1.0`

**OS**:

**Comment by kishorenc** [comment]
Fixed in `v0.3.0`
