### ISSUE TITLE
Method update by query not implemented

### ISSUE THREAD

**Issue by IPierrot** [typesense/typesense-java#54]
## Description

I want to update several documents with the documents().update(document, updateDocumentsParameters) method as described in the documentation : 
https://typesense.org/docs/0.25.2/api/documents.html#update-a-single-document
Unfortunately the method is not present in the class Documents.java
https://github.com/typesense/typesense-java/blob/master/src/main/java/org/typesense/api/Documents.java

## Steps to reproduce

Write the code written in the snippet in the documentation.

## Expected Behavior

The method is present and the code compiles

## Actual Behavior

The method is not present and the code does not compile

## Metadata

**Typesense Version**: 0.25.2
**Typesense-java Version**: 0.5.0

**Comment by IPierrot** [comment]
I saw that it is already merged in the master branch. My bad.

**Comment by kishorenc** [comment]
Available in `0.6.0` which has not been published.
