### ISSUE TITLE
Allow return the id of the imported documents

### ISSUE THREAD

**Issue by rpinzon** [typesense/typesense-java#55]
## Description

According to the [documentation](https://typesense.org/docs/latest/api/documents.html#returning-the-id-of-the-imported-documents) it's possible to configure the import response to return the ingested document's id in the response. To achieve this you can use the `return_id` parameter.

The `import_` function allows us to provide an instance of `ImportDocumentsParameters`. However, this class does not provide a way to configure the flag `return_id`.

## Steps to reproduce

Check the methods of `ImportDocumentsParameters` class.

## Expected Behavior

I expect to be able to configure the `return_id` flag using either a setter or a builder method within the `ImportDocumentsParameters` class.

For example:

Using setter method:

```
ImportDocumentsParameters params = new ImportDocumentsParameters();
params.setReturnId(true);
```

Using builder method:

```
ImportDocumentsParameters params = new ImportDocumentsParameters().returnId(true);
```

## Actual Behavior

It's not possible to configure the `return_id` flag.

## Metadata

**Typesense Version**: 0.25.2

**OS**: N/A

**Comment by shinusuresh** [comment]
@kishorenc  Looks like an issue with API spec. I don't see `return_id` in openapi spec.

**Comment by kishorenc** [comment]
Yes this needs to be added to the openapi spec so that it works with the Java client.
